name: openmhealth_schemas
description: A Flutter implementation of the Open mHealth (omh) schemas.
version: 0.0.4
author: CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/openmhealth_schemas

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^1.0.0
  uuid: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^0.10.0
  json_serializable: ^1.0.0

